### ISSUE TITLE
Check network connection failed. 

### ISSUE THREAD

**Issue by orcbolg3612** [sudorook/debian#3] opened 2024-01-25 15:06 UTC
keyhost@debian:~/debian$ ./postinstall
Checking network connection.

Cannot start network connection.

How to fix this error?

**Comment by sudorook** [comment] 2024-01-25 15:19
The script checks whether the network is active by attempting to connect to debian.org. Thinking offhand, if it's not working, it could be:

1. Your network is down/degraded. That doesn't seem to be the case, though, given that you're accessing this website.
2. debian.org is down or inaccessible. It seems unlikely, but if so, then changing the hard-coded url in `check_network()` defined in functions/00-check to a different site (perhaps github.com) will get around the issue.

**Comment by boteman** [comment] 2024-01-25 20:28
If it's unable to resolve debian.org the system might be unable to reach a proper DNS server.

**Comment by orcbolg3612** [comment] 2024-01-26 07:44
> The script checks whether the network is active by attempting to connect to debian.org. Thinking offhand, if it's not working, it could be:
> 
>     1. Your network is down/degraded. That doesn't seem to be the case, though, given that you're accessing this website.
> 
>     2. debian.org is down or inaccessible. It seems unlikely, but if so, then changing the hard-coded url in `check_network()` defined in functions/00-check to a different site (perhaps github.com) will get around the issue.

Can you give detailed instructions using the command line? I'm just an ordinary user who doesn't know much about computers.

**Comment by sudorook** [comment] 2024-01-26 16:27
The script is still reporting the network connection as having failed? I can
list a few things to try.

1. Check whether it is a DNS issue.

   All websites are addressable via an IP address, and a DNS (domain name
   server) - usually provided by your ISP - is what translates website names
   (e.g. google.com) to an IPv4/IPv6 numerical address (e.g. 142.250.191.238).
   Sometimes, this service fails, causing the translation from human-readable
   address to numerical address to fail and render the website inaccessible. To
   test whether this is happening to you, try to access a website by its name
   and again by its IP address. Open a terminal and run:

   ```sh
   ping debian.org
   ```

   ```sh
   ping 151.101.66.132
   ```

   If the former fails while the latter (the IP address to which for me
   debian.org resolves) succeeds, you have a DNS issue. If possible, try
   restarting your router, changing your DNS provider in your router settings,
   or just waiting to see if the problem gets resolved in time by your ISP.

   As an aside, if you don't know how to open a terminal, try searching
   'terminal' in your application menu and running whatever turns up.

2. Check whether debian.org is inaccessible to your IP address.

   Sometimes, sysadmins will block IP addresses due to a history of abuse of
   service (e.g. excessive web scraping, DoS attacks, etc.). This happens
   frequently when using shared addresses, such as those of a VPN server. Try
   running in the command line:

   ```sh
   curl -Is debian.org
   ```

   Check if the first line. If it returns code 403, your IP address has been
   blocked. Do what you can to change it and try again. Blocks may also be
   transient, so waiting and trying later may also work.

3. Your connection is poor and causes the network check to time out.

   Programs usually by default terminate a connection if it takes longer than a
   preset time to establish. This may happen if your internet connection is
   unusually poor or unstable. To check if curl (the program this script uses)
   is the cause, edit the curl command in the `check_network` function defined
   in 00-check:

   ```sh
   if curl -Is --retry 5 --retry-connrefused --connect-timeout 600 https://debian.org > /dev/null; then
   ```

   With the addition of `--connect-timeout`, the script will wait 5 minutes
   instead of whatever the default is before it exits with an error and makes
   the script fail.

   If the issue is not curl terminating but instead the server cutting the
   connection, there isn't anything that can be done on your end. Just keep
   trying.

4. (If on Wi-Fi) Poor Wi-Fi setup.

   Sometimes your system can default to an improper wireless networking
   protocol. It may be possible to force a desired protocol or disable an
   undesired protocol.

   Before going into more detail about this, note that if this is the issue, you
   need to know 1) the identity of your wireless card, and 2) the corresponding
   driver. Once you know 1), ensure that the driver from 2) is installed on your
   system.

   If you're using Debian stable or newer, the driver should be found in the
   `non-free-firmware` repository and already be installable via your package
   manager. If running an older release (I could be mistaken, I'm writing from
   memory), you will have to enable the `non-free` repository in your
   `/etc/apt/sources.list` file. This is done by adding 'non-free' to the end of
   every line starting with `deb`. If unsure of the release you are currently
   using, check the output from running `lsb_release -a` in the terminal.

   To get back to the original point, check the latest wireless protocol
   supported by your wireless card and the configuration options provided by
   your wireless card drivers. I've only used Intel cards and the corresponding
   `iwlwifi` driver, so I don't know about troubleshooting other cards.

   For example, if have an Intel card that supports 802.11ac, it may be
   defaulting to 802.11n. This can be disabled by creating a file in the
   `/etc/modprobe.d/` directory and adding the line:

   ```txt
   options iwlwifi 11n_disable=1
   ```

   Note this will require running as root. More detail for this specific
   example is available in the `disable_11n` function defined in 05-personal.
   For information for the card and the options available for its corresponding
   driver, you will need to look up the documentation wherever you can find it.

5. (If on Wi-Fi) Weak wireless connection.

   Move closer to your wireless access point. Alternatively, try connecting via
   Ethernet. Using Ethernet also allows you to circumvent having to
   troubleshoot wireless settings.

6. Disable the network check.

   Not all the functions provided in the script actually require network access.
   I just haven't bothered with making any of them available for use when the
   network check fails.

   If what you want to do doesn't require network access, open the `postinstall`
   script file in a text editor and remove the `check_network` command toward
   the bottom.

More exhaustive instructions others have doubtlessly written elsewhere.

**Closed as completed** 2024-01-26 17:35 UTC
